version: 2.1
jobs:
  failure_job:
    docker:
      - image: circleci/node:13.8.0

    steps:
      - run: return 1
      - run:
          name: Something failed
          command: echo "error"
          when: on_fail

    workflows:
      failed_job:
        jobs:
          - failure_job
